theme: jekyll-theme-architect
# By: Grayson Conger

I will be adding more projects here in the future, but for now here is TicTacToe.

https://github.com/GraysonConger/Projects/blob/main/TicTacToe/src/TicTacToe.java
